baseURL = 'https://stlamoureux1.github.io'
languageCode = 'en-us'
title = 'Spencer Lamoureux'

theme = 'moonwalk'

[menus]
    [[menus.main]]
        name = 'about'
        pageRef = '/about'

    [[menus.main]]
        name = 'blog'
        pageRef = '/blog'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            passthrough = { enable = true, delimiters = { block = [['$$', '$$']], inline = [['$', '$']] } }